# Lecture 11
Intorudction to numpy

🍂 Fall 2022, Alireza Imani

📚 Reference: [Python Data Science Handbook](https://www.oreilly.com/library/view/python-data-science/9781491912126/?sso_link=yes&sso_link_from=university-of-calgary)

**Please make sure you have `numpy` installed. For installing numpy, you may use [this guide](https://numpy.org/install/) on numpy website.**

**Please open IPython shell by entering `ipython` command in your terminal or open a new jupyter notebook using the `jupyter notebook` command.**

This chapter will cover NumPy in detail. NumPy (short for Numerical Python) provides
an efficient interface to store and operate on dense data buffers. In some ways,
NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much
more efficient storage and data operations as the arrays grow larger in size. NumPy
arrays form the core of nearly the entire ecosystem of data science tools in Python, so
time spent learning to use NumPy effectively will be valuable no matter what aspect
of data science interests you.

## Ensure numpy is installed

In [2]:
import numpy as np

In [3]:
np?

## Understanding Data Types in Python

Effective data-driven science and computation requires understanding how data is
stored and manipulated. This section outlines and contrasts how arrays of data are
handled in the Python language itself, and how NumPy **improves** it.

### Dynamic typing

In [ ]:
/* C code */
int result = 0;
for(int i=0; i<100; i++){
result += i;
}

int x = 4;
x = "four"; // FAILS

In [ ]:
# Python code
x = 4
x = "four"

Understanding how this works is an important
piece of learning to analyze data efficiently and effectively with Python. But what this
type flexibility also points to is the fact that **Python variables are more than just their
value**; they also contain **extra information** about the type of the value.

### A Python Integer Is More Than Just an Integer

A single integer in Python 3.4 actually contains four pieces:

* *ob_refcnt*, a reference count that helps Python silently handle memory allocation and deallocation.
* *ob_type*, which encodes the type of the variable.
* *ob_size*, which specifies the size of the following data members.
* *ob_digit*, which contains the actual integer value that we expect the Python variable to represent.

![The difference between C and Python integers](c-integer.jpg)

- A C integer is essentially a label for a position in memory whose bytes encode an integer value.

- A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value.

### A Python List Is More Than Just a List

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

This flexibility comes at a cost: to allow these flexible types, each item in the list
**must contain its own type info**, reference count, and other information—that is, each
item is a complete Python object. In the special case that all variables are of **the same
type**, much of this information is redundant: it can be much more efficient to store
data in a **fixed-type array**.



![The difference between C and Python lists](c-list.jpg)


The array essentially contains a single pointer to **one contiguous
block of data**. The Python list, on the other hand, contains a pointer to a
**block of pointers**, each of which in turn points to a **full Python object** like the Python
integer we saw earlier.

| List Type                     | Efficiency | Flexibility |
|-------------------------------|------------|-------------|
| Python List                   | ❌          | ✅           |
| Fixed-type NumPy-style arrays | ✅          | ❌           |


### Fixed-Type Arrays in Python

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

Much more useful, however, is the ***ndarray*** object of the NumPy package. While
Python’s array object provides efficient storage of array-based data, NumPy adds to
this efficient **operations** on that data.

### Creating Arrays from Python Lists

In [5]:
import numpy as np

In [6]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. If types do not match, NumPy will ***upcast*** if possible (here, integers are
upcast to floating point)

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines
built into NumPy.

In [11]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3, 3))

array([[0.72146642, 0.1024876 , 0.92529693],
       [0.62560813, 0.23621178, 0.81163305],
       [0.7962827 , 0.03199703, 0.79714434]])

In [17]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.38099375, -1.39454142,  1.1223363 ],
       [ 0.59928111, -2.78328658,  0.76639872],
       [-1.05305933, -1.14433893,  0.39640417]])

In [18]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 5, 3],
       [7, 8, 8],
       [0, 8, 1]])

In [20]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

### NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed
knowledge of those types and their limitations. Because NumPy is built in C, the
types will be familiar to users of C, Fortran, and other related languages.

![Numpy Standard Data Types](numpy-datatypes.jpeg)

<div style="text-align: center;">
Python DataScience HandBook - Page 41
</div>

In [22]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [23]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation:
even newer tools like Pandas (Chapter 3) are built around the NumPy array. This section
will present several examples using NumPy array manipulation to access data
and subarrays, and to split, reshape, and join the arrays.

### NumPy Array Attributes

In [24]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

print("x3 ndim: ", x3.ndim) # the number of dimensions
print("x3 shape:", x3.shape) # the size of each dimension
print("x3 size: ", x3.size) # the total size of the array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [25]:
print("dtype:", x3.dtype)

dtype: int64


In [26]:
print("itemsize:", x3.itemsize, "bytes")  # the size (in bytes) of each array element
print("nbytes:", x3.nbytes, "bytes")  # the total size (in bytes) of the array

itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing: Accessing Single Elements

Indexing for One-dimensional array is similar to list indexing in Python.

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
# First index -> First dimension (row in this case)
# Second index -> Second dimension (column in this case)

x2[0, 0]

3

In [32]:
x2[2, 0]

1

In [33]:
x2[-1, -3]

6

In [34]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [36]:
x1[0] = 3.14159 # this will be truncated because NumPy arrays have a fixed type.
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

x[`start`:`stop`:`step`]

If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1.

#### One-dimensional subarrays

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [39]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [40]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [44]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

When the step value is negative. In this case, **the defaults** for start and stop are swapped.

In [42]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

#### Multidimensional subarrays

In [45]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [47]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [48]:
x2[::-1, ::-1] # reverse all the dimensions

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

In [50]:
x2[:, 0] # first column of x2

array([12,  7,  1])

In [51]:
x2[0, :] # first row of x2

array([12,  5,  2,  4])

In [52]:
x2[0] # equivalent to x2[0, :]

array([12,  5,  2,  4])

#### Subarrays as no-copy views

One important—and extremely useful—thing to know about array slices is that they
return ***views*** rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies.

**If you modify an element in a subarray, the original array will be affected as well.**

This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer.

#### Creating copies of arrays

In [57]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[12,  5],
       [ 7,  6]])

In [55]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [56]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Reshaping of Arrays

In [60]:
one_to_nine = np.arange(1,10)
one_to_nine

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
grid = one_to_nine.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**The size of the initial array must match the size of the reshaped array.**

In [64]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [65]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [67]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [68]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [69]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines *np.concatenate*, *np.vstack*, and *np.hstack*.

#### Concatenation of arrays
#### concatenate()

In [72]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [73]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])

In [74]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### vstack()

In [76]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

#### hstack()

In [77]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.***dstack*** will stack arrays along the **third axis** (depth).

In [78]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


#### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit. For each of these, we can pass **a list of indices
giving the split points**.

#### split()

In [79]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


#### vsplit()  - vertical splitting

In [81]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
upper, lower = np.vsplit(grid, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### hsplit() - horizontal splitting

In [85]:
left, right = np.hsplit(grid, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [86]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

Similarly, np.*dsplit* will split arrays along the third axis.

## Computation on NumPy Arrays: Universal Functions

Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use vectorized operations, generally implemented through Num‐
Py’s universal functions (ufuncs). This section motivates the need for NumPy’s ufuncs,
which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs
available in the NumPy package.

In [89]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [94]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

895 ms ± 5.43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


It turns
out that the bottleneck here is not the operations themselves, but the **type-checking**
and **function dispatches** that CPython must do at each cycle of the loop. Each time
the reciprocal is computed, Python first examines the object’s type and does a
dynamic lookup of the correct function to use for that type. If we were working in
compiled code instead, this type specification would be known before the code executes
and the result could be computed much more efficiently.

### UFuncs

For many types of operations, NumPy provides a convenient interface into just this
kind of statically typed, compiled routine. This is known as a ***vectorized operation***.
You can accomplish this by simply **performing an operation on the array**, which will
then be applied to **each element**.

In [91]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [95]:
%timeit (1.0 / big_array)  # ~14 times faster!

753 µs ± 96.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [96]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [97]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Exploring NumPy’s UFuncs

Ufuncs exist in two flavors: 

- ***Unary ufuncs***: Operate on a single input.
- ***Binary ufuncs***: Operate on two inputs.

#### Array arithmetic

In [100]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [101]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [102]:
np.add(x, 2)

array([2, 3, 4, 5])

![](arithmatic-operators.jpeg)

<div style="text-align: center;">
Python DataScience HandBook - Page 53
</div>

#### Absolute value

In [103]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [104]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [105]:
np.abs(x)

array([2, 1, 0, 1, 2])

#### Trigonometric functions

In [109]:
theta = np.linspace(0, np.pi, 3)

print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that
should be zero do not always hit exactly zero.

In [108]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and logarithms

In [110]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [111]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [112]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


> When x is very small, these functions give more precise values than if the raw np.log
or np.exp were used.

### Advanced Ufunc Features

---


#### Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the
result of the calculation will be stored. Rather than creating a temporary array, you
can use this to write computation results directly to the memory location where you’d like them to be. For all ufuncs, you can do this using the `out` argument of the
function.

In [115]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

array([ 0., 10., 20., 30., 40.])

In [116]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

If we had instead written `y[::2] = 2 ** x`, this would have resulted in:

1. The creation of a temporary array to hold the results of 2 ** x.
2. A second operation copying those values into the y array. 

This doesn’t make much of a difference for such
a small computation, but for very large arrays the memory savings from careful use of
the out argument can be significant.

#### Aggregates

For binary ufuncs, there are some interesting *aggregates* that can be computed
directly from the object. For example, if we’d like to *reduce* an array with a particular
operation, we can use the `reduce` method of any ufunc. A reduce **repeatedly applies a
given operation to the elements of an array** until only **a single result** remains.

In [117]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [118]:
np.multiply.reduce(x)

120

In [120]:
np.add.accumulate(x)  # stores all the intermediate results of the computation

array([ 1,  3,  6, 10, 15])

#### Outer products

Finally, any ufunc can compute the output of all pairs of two different inputs using
the `outer` method. This allows you, in one line, to do things like create a multiplication
table:

In [121]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Ufuncs: Learning More

More information on universal functions (including the full list of available functions)
can be found on the [NumPy](https://numpy.org) and [SciPy](https://scipy.org) documentation websites.